# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1d0a449aac512465d6978982fd50280"
name = "subscribe-sms"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_write_customers,write_app_proxy,write_customers,write_gift_cards,write_products,write_products,read_purchase_options,write_purchase_options,read_own_subscription_contracts,write_own_subscription_contracts,read_customer_payment_methods,read_customers,read_orders,read_all_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "/customapi"
prefix = "apps"
subpath = "customapi"